name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-textreplacer:
    name: Build TextReplacer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: textreplacer
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://npm.pkg.github.com"
          scope: "@izumiano"
      - run: npm i
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm test
      - run: npm run build
      - uses: actions/upload-artifact@v7
        with:
          name: release-textreplacer
          path: textreplacer/dist
  
  build-configure:
    name: Build Configure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: configure
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://npm.pkg.github.com"
          scope: "@izumiano"
      - run: npm i
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm test
      - run: npm run build
      - uses: actions/upload-artifact@v7
        with:
          name: release-configure
          path: configure/dist

  release:
    runs-on: ubuntu-latest
    needs: [build-textreplacer, build-configure]
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v7
        with:
          pattern: release-*
          path: .
      - uses: ncipollo/release-action@v1
        with:
          artifacts: release-*/*
          omitBody: true